name: LunaticStorage
version: '${project.version}'
main: net.professoradam.lunaticstorage.LunaticStorage
api-version: '1.19'
softdepend: ProfessorAdamGeldPlugin
commands:
  lunaticstorage:
    description: Open storage command
    usage: /storage
    aliases:
      - storage
depend:
  - LunaticLib