name: LunaticStorage
version: '${project.version}'
main: de.janschuri.lunaticstorage.LunaticStoragePlugin
api-version: '1.21'
softdepend: ProfessorAdamGeldPlugin
commands:
  lunaticstorage:
    description: Open storage command
    usage: /storage
    aliases:
      - storage
depend:
  - LunaticLib
